// ── Floating Tech-Stack KB Badge Configs ─────────────────────────────────
// Each array maps to the hero floating badge slots (slot-1 … slot-6)
// for dynamic [type]/[subcategory] pages that use the fallback generator.

export type FloatingBadge = {
  name: string;
  label?: string;
  iconClass: string;
  color: string;
  borderColor: string;
};

export const subcategoryFloatingBadgesMap: Record<string, FloatingBadge[]> = {

  // ══════════════ APP DEVELOPMENT ══════════════
  "android-application": [
    { name: "Android",      iconClass: "fa-brands fa-android",              color: "#3ddc84", borderColor: "rgba(61,220,132,0.4)" },
    { name: "Kotlin",       iconClass: "fa-solid fa-k",                     color: "#7f52ff", borderColor: "rgba(127,82,255,0.4)" },
    { name: "Java",         iconClass: "fa-brands fa-java",                  color: "#f89820", borderColor: "rgba(248,152,32,0.4)" },
    { name: "Firebase",     iconClass: "fa-solid fa-fire",                  color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"  },
    { name: "React Native", iconClass: "fa-brands fa-react",                color: "#00d8ff", borderColor: "rgba(0,216,255,0.4)"  },
    { name: "Play Store",   iconClass: "fa-brands fa-google-play",          color: "#4285f4", borderColor: "rgba(66,133,244,0.4)" },
  ],
  "ios-application": [
    { name: "Swift",     iconClass: "fa-brands fa-apple",              color: "#555555", borderColor: "rgba(85,85,85,0.4)"   },
    { name: "iOS SDK",   label: "iOS", iconClass: "fa-solid fa-mobile-screen-button", color: "#007aff", borderColor: "rgba(0,122,255,0.4)"  },
    { name: "Xcode",     iconClass: "fa-solid fa-hammer",              color: "#1d7aff", borderColor: "rgba(29,122,255,0.4)"  },
    { name: "Firebase",  iconClass: "fa-solid fa-fire",                color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"  },
    { name: "CoreData",  iconClass: "fa-solid fa-database",            color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
    { name: "App Store", iconClass: "fa-brands fa-app-store-ios",     color: "#007aff", borderColor: "rgba(0,122,255,0.4)"  },
  ],
  "react-native": [
    { name: "React Native", iconClass: "fa-brands fa-react",          color: "#00d8ff", borderColor: "rgba(0,216,255,0.4)"  },
    { name: "JS",           iconClass: "fa-brands fa-js",             color: "#f7df1e", borderColor: "rgba(247,223,30,0.5)" },
    { name: "Expo",         iconClass: "fa-solid fa-layer-group",     color: "#000020", borderColor: "rgba(0,0,32,0.4)"     },
    { name: "Firebase",     iconClass: "fa-solid fa-fire",            color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"  },
    { name: "Node.js",      iconClass: "fa-brands fa-node-js",        color: "#339933", borderColor: "rgba(51,153,51,0.4)"  },
    { name: "Android",      iconClass: "fa-brands fa-android",        color: "#3ddc84", borderColor: "rgba(61,220,132,0.4)" },
  ],
  "flutter-app-development": [
    { name: "Flutter",   iconClass: "fa-solid fa-mobile-screen-button", color: "#54c5f8", borderColor: "rgba(84,197,248,0.4)" },
    { name: "Dart",      iconClass: "fa-solid fa-code",                color: "#0175c2", borderColor: "rgba(1,117,194,0.4)"  },
    { name: "Firebase",  iconClass: "fa-solid fa-fire",                color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"  },
    { name: "Android",   iconClass: "fa-brands fa-android",            color: "#3ddc84", borderColor: "rgba(61,220,132,0.4)" },
    { name: "iOS",       iconClass: "fa-brands fa-apple",              color: "#555555", borderColor: "rgba(85,85,85,0.4)"   },
    { name: "REST APIs", iconClass: "fa-solid fa-circle-nodes",        color: "#e10098", borderColor: "rgba(225,0,152,0.4)"  },
  ],

  // ══════════════ PPC ══════════════
  "google-ads": [
    { name: "Google Ads",   iconClass: "fa-brands fa-google",                   color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Search Ads",   iconClass: "fa-solid fa-magnifying-glass-dollar",   color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Display",      iconClass: "fa-solid fa-display",                   color: "#fbbc05", borderColor: "rgba(251,188,5,0.5)"   },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",                color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Tag Manager",  iconClass: "fa-solid fa-tags",                      color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Remarketing",  iconClass: "fa-solid fa-rotate",                    color: "#ea4335", borderColor: "rgba(234,67,53,0.4)"   },
  ],
  "facebook-ads": [
    { name: "Facebook Ads",  iconClass: "fa-brands fa-facebook-f",  color: "#1877f2", borderColor: "rgba(24,119,242,0.4)"  },
    { name: "Meta Ads",      iconClass: "fa-brands fa-meta",         color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Instagram Ads", iconClass: "fa-brands fa-instagram",    color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "Pixel",         iconClass: "fa-solid fa-code",          color: "#1877f2", borderColor: "rgba(24,119,242,0.4)"  },
    { name: "Ads Manager",   iconClass: "fa-solid fa-chart-column",  color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Analytics",     iconClass: "fa-solid fa-chart-line",    color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
  ],
  "display-advertising": [
    { name: "Google Display", iconClass: "fa-brands fa-google",               color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Banner Ads",     iconClass: "fa-solid fa-rectangle-ad",          color: "#fbbc05", borderColor: "rgba(251,188,5,0.5)"   },
    { name: "Programmatic",   iconClass: "fa-solid fa-gears",                 color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Analytics",      iconClass: "fa-solid fa-chart-line",            color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Retargeting",    iconClass: "fa-solid fa-rotate",                color: "#ea4335", borderColor: "rgba(234,67,53,0.4)"   },
    { name: "DSP",            iconClass: "fa-solid fa-server",                color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "remarketing-campaigns": [
    { name: "Google Ads",   iconClass: "fa-brands fa-google",       color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Facebook",     iconClass: "fa-brands fa-facebook-f",   color: "#1877f2", borderColor: "rgba(24,119,242,0.4)"  },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",    color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Pixel",        iconClass: "fa-solid fa-code",          color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "CRM",          iconClass: "fa-solid fa-users",         color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Automation",   iconClass: "fa-solid fa-robot",         color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],

  // ══════════════ SOFTWARE DEVELOPMENT ══════════════
  "software-development": [
    { name: "React",    iconClass: "fa-brands fa-react",    color: "#00d8ff", borderColor: "rgba(0,216,255,0.4)"  },
    { name: "Node.js",  iconClass: "fa-brands fa-node-js",  color: "#339933", borderColor: "rgba(51,153,51,0.4)"  },
    { name: "Python",   iconClass: "fa-brands fa-python",   color: "#3776ab", borderColor: "rgba(55,118,171,0.4)" },
    { name: "Docker",   iconClass: "fa-brands fa-docker",   color: "#2496ed", borderColor: "rgba(36,150,237,0.4)" },
    { name: "AWS",      iconClass: "fa-brands fa-aws",      color: "#ff9900", borderColor: "rgba(255,153,0,0.4)"  },
    { name: "MongoDB",  iconClass: "fa-solid fa-leaf",      color: "#47a248", borderColor: "rgba(71,162,72,0.4)"  },
  ],
  "ai-automations": [
    { name: "Python",    iconClass: "fa-brands fa-python",          color: "#3776ab", borderColor: "rgba(55,118,171,0.4)"  },
    { name: "AI / ML",   iconClass: "fa-solid fa-brain",            color: "#a855f7", borderColor: "rgba(168,85,247,0.4)"  },
    { name: "OpenAI",    iconClass: "fa-solid fa-robot",            color: "#10a37f", borderColor: "rgba(16,163,127,0.4)"  },
    { name: "LangChain", iconClass: "fa-solid fa-link",             color: "#1c1c1e", borderColor: "rgba(28,28,30,0.4)"    },
    { name: "FastAPI",   iconClass: "fa-solid fa-bolt",             color: "#009688", borderColor: "rgba(0,150,136,0.4)"   },
    { name: "Docker",    iconClass: "fa-brands fa-docker",          color: "#2496ed", borderColor: "rgba(36,150,237,0.4)"  },
  ],

  // ══════════════ DIGITAL MARKETING ══════════════
  "search-engine-optimization": [
    { name: "Google",         iconClass: "fa-brands fa-google",                   color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "SEMrush",        iconClass: "fa-solid fa-magnifying-glass-chart",    color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
    { name: "Ahrefs",         iconClass: "fa-solid fa-chart-bar",                 color: "#ff7043", borderColor: "rgba(255,112,67,0.4)"  },
    { name: "GA4",            iconClass: "fa-solid fa-chart-line",                color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Search Console", iconClass: "fa-solid fa-magnifying-glass",          color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Yoast SEO",      iconClass: "fa-brands fa-wordpress",               color: "#a4286a", borderColor: "rgba(164,40,106,0.4)"  },
  ],
  "search-engine-marketing": [
    { name: "Google Ads",   iconClass: "fa-brands fa-google",                   color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Bing Ads",     iconClass: "fa-brands fa-microsoft",                color: "#00809d", borderColor: "rgba(0,128,157,0.4)"   },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",                color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Tag Manager",  iconClass: "fa-solid fa-tags",                      color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Keywords",     iconClass: "fa-solid fa-magnifying-glass-dollar",   color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Remarketing",  iconClass: "fa-solid fa-rotate",                    color: "#ea4335", borderColor: "rgba(234,67,53,0.4)"   },
  ],
  "social-media-marketing": [
    { name: "Facebook",   iconClass: "fa-brands fa-facebook-f",    color: "#1877f2", borderColor: "rgba(24,119,242,0.4)"  },
    { name: "Instagram",  iconClass: "fa-brands fa-instagram",     color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "LinkedIn",   iconClass: "fa-brands fa-linkedin-in",   color: "#0a66c2", borderColor: "rgba(10,102,194,0.4)"  },
    { name: "YouTube",    iconClass: "fa-brands fa-youtube",       color: "#ff0000", borderColor: "rgba(255,0,0,0.4)"     },
    { name: "Analytics",  iconClass: "fa-solid fa-chart-line",     color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Hootsuite",  iconClass: "fa-solid fa-calendar-check", color: "#1f8dd6", borderColor: "rgba(31,141,214,0.4)"  },
  ],
  "sms-marketing": [
    { name: "Twilio",     iconClass: "fa-solid fa-comment-sms",    color: "#f22f46", borderColor: "rgba(242,47,70,0.4)"   },
    { name: "SMS API",    iconClass: "fa-solid fa-mobile-screen",  color: "#00b5d8", borderColor: "rgba(0,181,216,0.4)"   },
    { name: "CRM",        iconClass: "fa-solid fa-users",          color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
    { name: "Automation", iconClass: "fa-solid fa-robot",          color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Analytics",  iconClass: "fa-solid fa-chart-line",     color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Bulk SMS",   iconClass: "fa-solid fa-paper-plane",    color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
  ],
  "facebook-marketing": [
    { name: "Facebook",    iconClass: "fa-brands fa-facebook-f",   color: "#1877f2", borderColor: "rgba(24,119,242,0.4)"  },
    { name: "Meta Ads",    iconClass: "fa-brands fa-meta",          color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Instagram",   iconClass: "fa-brands fa-instagram",    color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "Pixel",       iconClass: "fa-solid fa-code",          color: "#1877f2", borderColor: "rgba(24,119,242,0.4)"  },
    { name: "Ads Manager", iconClass: "fa-solid fa-chart-column",  color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Analytics",   iconClass: "fa-solid fa-chart-line",    color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
  ],
  "content-marketing": [
    { name: "WordPress",  iconClass: "fa-brands fa-wordpress",  color: "#21759b", borderColor: "rgba(33,117,155,0.4)"  },
    { name: "SEO",        iconClass: "fa-solid fa-magnifying-glass", color: "#4285f4", borderColor: "rgba(66,133,244,0.4)" },
    { name: "Canva",      iconClass: "fa-solid fa-palette",      color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
    { name: "Analytics",  iconClass: "fa-solid fa-chart-line",   color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "HubSpot",    iconClass: "fa-brands fa-hubspot",     color: "#ff7a59", borderColor: "rgba(255,122,89,0.4)"  },
    { name: "Mailchimp",  iconClass: "fa-solid fa-envelope",     color: "#ffe01b", borderColor: "rgba(255,224,27,0.5)"  },
  ],

  // ══════════════ LOCAL SEO ══════════════
  "on-page-optimization": [
    { name: "HTML",     label: "HTML", iconClass: "fa-brands fa-html5",              color: "#e34f26", borderColor: "rgba(227,79,38,0.4)"   },
    { name: "Meta Tags",              iconClass: "fa-solid fa-tags",                  color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Schema",                 iconClass: "fa-solid fa-code",                  color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
    { name: "Speed",                  iconClass: "fa-solid fa-gauge-high",            color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Google",                 iconClass: "fa-brands fa-google",               color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "SEMrush",                iconClass: "fa-solid fa-magnifying-glass-chart",color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
  ],
  "off-page-optimization": [
    { name: "Backlinks",        iconClass: "fa-solid fa-link",          color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Ahrefs",           iconClass: "fa-solid fa-chart-bar",     color: "#ff7043", borderColor: "rgba(255,112,67,0.4)"  },
    { name: "Domain Authority", iconClass: "fa-solid fa-award",         color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
    { name: "Google",           iconClass: "fa-brands fa-google",       color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Moz",              iconClass: "fa-solid fa-chart-simple",  color: "#00b4f0", borderColor: "rgba(0,180,240,0.4)"   },
    { name: "Press Release",    iconClass: "fa-solid fa-newspaper",     color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "technical-seo": [
    { name: "Google",          iconClass: "fa-brands fa-google",                   color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Search Console",  iconClass: "fa-solid fa-magnifying-glass",          color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Lighthouse",      iconClass: "fa-solid fa-circle-check",             color: "#ff9955", borderColor: "rgba(255,153,85,0.4)"  },
    { name: "Schema",          iconClass: "fa-solid fa-code",                     color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
    { name: "Core Web Vitals", iconClass: "fa-solid fa-gauge-high",              color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Sitemap",         iconClass: "fa-solid fa-map",                     color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],

  // ══════════════ SOCIAL MEDIA MARKETING subcategories ══════════════
  "branding": [
    { name: "Figma",          iconClass: "fa-brands fa-figma",          color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"   },
    { name: "Illustrator",    iconClass: "fa-solid fa-pen-nib",         color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"   },
    { name: "Photoshop",      iconClass: "fa-solid fa-image",           color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)"  },
    { name: "Canva",          iconClass: "fa-solid fa-palette",         color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
    { name: "Logo Design",    iconClass: "fa-solid fa-star",            color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
    { name: "Brand Identity", iconClass: "fa-solid fa-fingerprint",     color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "instagram-marketing": [
    { name: "Instagram", iconClass: "fa-brands fa-instagram",  color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "Reels",     iconClass: "fa-solid fa-film",         color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "Stories",   iconClass: "fa-solid fa-circle-play",  color: "#833ab4", borderColor: "rgba(131,58,180,0.4)"  },
    { name: "Meta Ads",  iconClass: "fa-brands fa-meta",        color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Analytics", iconClass: "fa-solid fa-chart-line",   color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Canva",     iconClass: "fa-solid fa-palette",      color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
  ],
  "youtube-marketing": [
    { name: "YouTube",      iconClass: "fa-brands fa-youtube",        color: "#ff0000", borderColor: "rgba(255,0,0,0.4)"     },
    { name: "Video SEO",    iconClass: "fa-solid fa-magnifying-glass", color: "#ff0000", borderColor: "rgba(255,0,0,0.4)"    },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",       color: "#e37400", borderColor: "rgba(227,116,0,0.4)"  },
    { name: "YouTube Ads",  iconClass: "fa-brands fa-google",          color: "#4285f4", borderColor: "rgba(66,133,244,0.4)" },
    { name: "Thumbnails",   iconClass: "fa-solid fa-image",            color: "#ff5722", borderColor: "rgba(255,87,34,0.4)"  },
    { name: "Premiere Pro", iconClass: "fa-solid fa-film",             color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
  ],
  "linkedin-marketing": [
    { name: "LinkedIn",     iconClass: "fa-brands fa-linkedin-in",  color: "#0a66c2", borderColor: "rgba(10,102,194,0.4)"  },
    { name: "B2B Ads",      iconClass: "fa-solid fa-briefcase",     color: "#0a66c2", borderColor: "rgba(10,102,194,0.4)"  },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",    color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Campaign Mgr", iconClass: "fa-solid fa-bullhorn",      color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Lead Gen",     iconClass: "fa-solid fa-user-plus",     color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Content",      iconClass: "fa-solid fa-pen-to-square", color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "twitter-marketing": [
    { name: "X / Twitter",  iconClass: "fa-brands fa-x-twitter",       color: "#1da1f2", borderColor: "rgba(29,161,242,0.4)"  },
    { name: "Twitter Ads",  iconClass: "fa-solid fa-bullseye",          color: "#1da1f2", borderColor: "rgba(29,161,242,0.4)"  },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",        color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Trending",     iconClass: "fa-solid fa-arrow-trend-up",    color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "Engagement",   iconClass: "fa-solid fa-heart",             color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "Scheduling",   iconClass: "fa-solid fa-calendar-check",    color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "social-media-advertising": [
    { name: "Meta Ads",     iconClass: "fa-brands fa-meta",           color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
    { name: "Google Ads",   iconClass: "fa-brands fa-google",         color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "LinkedIn Ads", iconClass: "fa-brands fa-linkedin-in",    color: "#0a66c2", borderColor: "rgba(10,102,194,0.4)"  },
    { name: "YouTube Ads",  iconClass: "fa-brands fa-youtube",        color: "#ff0000", borderColor: "rgba(255,0,0,0.4)"     },
    { name: "Analytics",    iconClass: "fa-solid fa-chart-line",      color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Retargeting",  iconClass: "fa-solid fa-rotate",          color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "social-media-post-scheduling": [
    { name: "Hootsuite",     iconClass: "fa-solid fa-calendar-check",  color: "#1f8dd6", borderColor: "rgba(31,141,214,0.4)"  },
    { name: "Buffer",        iconClass: "fa-solid fa-clock",           color: "#168eea", borderColor: "rgba(22,142,234,0.4)"  },
    { name: "Later",         iconClass: "fa-brands fa-instagram",      color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "Canva",         iconClass: "fa-solid fa-palette",         color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
    { name: "Analytics",     iconClass: "fa-solid fa-chart-line",      color: "#e37400", borderColor: "rgba(227,116,0,0.4)"   },
    { name: "Meta Planner",  iconClass: "fa-brands fa-meta",           color: "#0082fb", borderColor: "rgba(0,130,251,0.4)"   },
  ],

  // ══════════════ LOCAL SEO ══════════════
  "google-my-business-ranking": [
    { name: "Google",     iconClass: "fa-brands fa-google",                 color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Google Maps",iconClass: "fa-solid fa-map-location-dot",        color: "#34a853", borderColor: "rgba(52,168,83,0.4)"   },
    { name: "GMB Profile",iconClass: "fa-solid fa-store",                   color: "#fbbc05", borderColor: "rgba(251,188,5,0.5)"   },
    { name: "Reviews",    iconClass: "fa-solid fa-star",                    color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"   },
    { name: "Local SEO",  iconClass: "fa-solid fa-magnifying-glass-location",color: "#ea4335",borderColor: "rgba(234,67,53,0.4)"  },
    { name: "Citations",  iconClass: "fa-solid fa-link",                    color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "local-directory-listings": [
    { name: "Google",    iconClass: "fa-brands fa-google",      color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Yelp",      iconClass: "fa-brands fa-yelp",        color: "#d32323", borderColor: "rgba(211,35,35,0.4)"   },
    { name: "Bing Places",iconClass: "fa-brands fa-microsoft",  color: "#00809d", borderColor: "rgba(0,128,157,0.4)"   },
    { name: "Local SEO", iconClass: "fa-solid fa-map-location-dot", color: "#34a853", borderColor: "rgba(52,168,83,0.4)" },
    { name: "Citations", iconClass: "fa-solid fa-link",         color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
    { name: "NAP Audit", iconClass: "fa-solid fa-address-card", color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
  ],
  "local-seo-tools": [
    { name: "SEMrush",    iconClass: "fa-solid fa-magnifying-glass-chart", color: "#ff642d", borderColor: "rgba(255,100,45,0.4)"  },
    { name: "Moz Local",  iconClass: "fa-solid fa-chart-simple",           color: "#00b4f0", borderColor: "rgba(0,180,240,0.4)"   },
    { name: "BrightLocal",iconClass: "fa-solid fa-location-dot",           color: "#ff5722", borderColor: "rgba(255,87,34,0.4)"   },
    { name: "Google",     iconClass: "fa-brands fa-google",                color: "#4285f4", borderColor: "rgba(66,133,244,0.4)"  },
    { name: "Ahrefs",     iconClass: "fa-solid fa-chart-bar",              color: "#ff7043", borderColor: "rgba(255,112,67,0.4)"  },
    { name: "WhiteSpark", iconClass: "fa-solid fa-star",                   color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],

  // ══════════════ VIDEO EDITING ══════════════
  "reel-videos": [
    { name: "Premiere Pro", iconClass: "fa-solid fa-film",                color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "After Effects",iconClass: "fa-solid fa-wand-magic-sparkles", color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "Instagram",    iconClass: "fa-brands fa-instagram",          color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
    { name: "CapCut",       iconClass: "fa-solid fa-video",               color: "#333333", borderColor: "rgba(51,51,51,0.4)"    },
    { name: "Motion",       iconClass: "fa-solid fa-circle-play",         color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"   },
    { name: "Canva",        iconClass: "fa-solid fa-palette",             color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
  ],
  "model-shoot-videos": [
    { name: "Premiere Pro", iconClass: "fa-solid fa-film",                color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "DaVinci",      iconClass: "fa-solid fa-circle-play",         color: "#e50914", borderColor: "rgba(229,9,20,0.4)"    },
    { name: "Color Grading",iconClass: "fa-solid fa-palette",             color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"   },
    { name: "After Effects",iconClass: "fa-solid fa-wand-magic-sparkles", color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "Lightroom",    iconClass: "fa-solid fa-sun",                 color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)"  },
    { name: "4K Video",     iconClass: "fa-solid fa-video",               color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "realestate-drone-shots": [
    { name: "DJI Drone",    iconClass: "fa-solid fa-helicopter",          color: "#333333", borderColor: "rgba(51,51,51,0.4)"    },
    { name: "DaVinci",      iconClass: "fa-solid fa-circle-play",         color: "#e50914", borderColor: "rgba(229,9,20,0.4)"    },
    { name: "Premiere Pro", iconClass: "fa-solid fa-film",                color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "After Effects",iconClass: "fa-solid fa-wand-magic-sparkles", color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "LUTs",         iconClass: "fa-solid fa-palette",             color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"   },
    { name: "4K HDR",       iconClass: "fa-solid fa-video",               color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "custom-videos": [
    { name: "Premiere Pro",   iconClass: "fa-solid fa-film",                color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "After Effects",  iconClass: "fa-solid fa-wand-magic-sparkles", color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "Motion Graphics",iconClass: "fa-solid fa-circle-play",         color: "#ff9800", borderColor: "rgba(255,152,0,0.4)"   },
    { name: "DaVinci",        iconClass: "fa-solid fa-circle-play",         color: "#e50914", borderColor: "rgba(229,9,20,0.4)"    },
    { name: "4K Video",       iconClass: "fa-solid fa-video",               color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
    { name: "Canva",          iconClass: "fa-solid fa-palette",             color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
  ],

  // ══════════════ GRAPHIC DESIGNING ══════════════
  "logo-designs": [
    { name: "Illustrator",   iconClass: "fa-solid fa-pen-nib",        color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"   },
    { name: "Photoshop",     iconClass: "fa-solid fa-image",          color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)"  },
    { name: "Figma",         iconClass: "fa-brands fa-figma",         color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"   },
    { name: "Canva",         iconClass: "fa-solid fa-palette",        color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
    { name: "CorelDRAW",     iconClass: "fa-solid fa-vector-square",  color: "#006633", borderColor: "rgba(0,102,51,0.4)"    },
    { name: "Brand Identity",iconClass: "fa-solid fa-fingerprint",    color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"   },
  ],
  "package-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",       color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",         color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "3D Mockup",   iconClass: "fa-solid fa-cube",          color: "#ff5722", borderColor: "rgba(255,87,34,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",    color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Canva",       iconClass: "fa-solid fa-palette",       color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",         color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "social-media-designs": [
    { name: "Canva",        iconClass: "fa-solid fa-palette",             color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"   },
    { name: "Figma",        iconClass: "fa-brands fa-figma",              color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"   },
    { name: "Photoshop",    iconClass: "fa-solid fa-image",               color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)"  },
    { name: "Illustrator",  iconClass: "fa-solid fa-pen-nib",             color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"   },
    { name: "After Effects",iconClass: "fa-solid fa-wand-magic-sparkles", color: "#9999ff", borderColor: "rgba(153,153,255,0.4)" },
    { name: "Instagram",    iconClass: "fa-brands fa-instagram",          color: "#e1306c", borderColor: "rgba(225,48,108,0.4)"  },
  ],
  "brochure-designs": [
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "pamphlet-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "website-banners": [
    { name: "Figma",       iconClass: "fa-brands fa-figma",       color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",      color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",        color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "HTML",  label:"HTML", iconClass: "fa-brands fa-html5",color: "#e34f26", borderColor: "rgba(227,79,38,0.4)" },
    { name: "CSS",   label:"CSS",  iconClass: "fa-brands fa-css3-alt", color: "#1572b6", borderColor: "rgba(21,114,182,0.4)" },
    { name: "Canva",       iconClass: "fa-solid fa-palette",      color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
  ],
  "banner-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "2d-3d-designs": [
    { name: "Blender",    iconClass: "fa-solid fa-cube",              color: "#f5792a", borderColor: "rgba(245,121,42,0.4)"  },
    { name: "Maya",       iconClass: "fa-solid fa-cubes",             color: "#1b8cbe", borderColor: "rgba(27,140,190,0.4)"  },
    { name: "3ds Max",    iconClass: "fa-solid fa-cube",              color: "#d64000", borderColor: "rgba(214,64,0,0.4)"    },
    { name: "AutoCAD",    iconClass: "fa-solid fa-drafting-compass",  color: "#e5002b", borderColor: "rgba(229,0,43,0.4)"    },
    { name: "Cinema 4D",  iconClass: "fa-solid fa-film",              color: "#011a6a", borderColor: "rgba(1,26,106,0.4)"    },
    { name: "Illustrator",iconClass: "fa-solid fa-pen-nib",           color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"   },
  ],
  "standee-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "creative-business-card-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "annual-report-design": [
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Data Viz",    iconClass: "fa-solid fa-chart-pie",   color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "end-to-end-event-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "3D Mockup",   iconClass: "fa-solid fa-cube",        color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "csr-report-design": [
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Data Viz",    iconClass: "fa-solid fa-chart-pie",   color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "strategy-report-design": [
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",      color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",         color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Figma",       iconClass: "fa-brands fa-figma",          color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "PowerPoint",  iconClass: "fa-solid fa-file-powerpoint", color: "#d24726", borderColor: "rgba(210,71,38,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",         color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Data Viz",    iconClass: "fa-solid fa-chart-pie",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  // Typo variant from user: "rategy" → same as strategy
  "rategy-report-design": [
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",      color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",         color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Figma",       iconClass: "fa-brands fa-figma",          color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "PowerPoint",  iconClass: "fa-solid fa-file-powerpoint", color: "#d24726", borderColor: "rgba(210,71,38,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",         color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Data Viz",    iconClass: "fa-solid fa-chart-pie",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "catalogue-designs": [
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "menu-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "marriage-card-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",     color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",       color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "Canva",       iconClass: "fa-solid fa-palette",     color: "#00c4cc", borderColor: "rgba(0,196,204,0.4)"  },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",  color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",      color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "Print Ready", iconClass: "fa-solid fa-print",       color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "hoarding-billboard-designs": [
    { name: "Illustrator", iconClass: "fa-solid fa-pen-nib",        color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Photoshop",   iconClass: "fa-solid fa-image",          color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)" },
    { name: "InDesign",    iconClass: "fa-solid fa-file-lines",     color: "#ff3366", borderColor: "rgba(255,51,102,0.4)" },
    { name: "Figma",       iconClass: "fa-brands fa-figma",         color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"  },
    { name: "CorelDRAW",   iconClass: "fa-solid fa-vector-square",  color: "#006633", borderColor: "rgba(0,102,51,0.4)"   },
    { name: "Large Format",iconClass: "fa-solid fa-expand",         color: "#5856d6", borderColor: "rgba(88,86,214,0.4)"  },
  ],
  "illustrations": [
    { name: "Illustrator",  iconClass: "fa-solid fa-pen-nib",           color: "#ff9a00", borderColor: "rgba(255,154,0,0.4)"  },
    { name: "Procreate",    iconClass: "fa-solid fa-pencil",            color: "#1d1d1f", borderColor: "rgba(29,29,31,0.4)"    },
    { name: "Photoshop",    iconClass: "fa-solid fa-image",             color: "#31a8ff", borderColor: "rgba(49,168,255,0.4)"  },
    { name: "Figma",        iconClass: "fa-brands fa-figma",            color: "#f24e1e", borderColor: "rgba(242,78,30,0.4)"   },
    { name: "Clip Studio",  iconClass: "fa-solid fa-paintbrush",        color: "#e91e63", borderColor: "rgba(233,30,99,0.4)"   },
    { name: "Digital Art",  iconClass: "fa-solid fa-wand-magic-sparkles",color: "#9c27b0",borderColor: "rgba(156,39,176,0.4)"  },
  ],
};
